name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pwsh build.ps1
      - uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: pages
          folder: build
