name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: pwsh ps1/build-1.ps1
      - run: php php/build.php
      - run: pwsh ps1/build-2.ps1

      - uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: pages
          folder: build
