name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: pwsh ps1/build-1.ps1
      - run: php php/build.php
      - run: pwsh ps1/build-2.ps1

      - run: git config user.name "github-actions[bot]"
      - run: git config user.email "github-actions[bot]@users.noreply.github.com"

      - run: git add -A
      - run: git commit -m "Build and Deploy"
      - run: git push
